# Generated by Django 6.0.6 on 2026-06-13 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_rename_comentario_comentent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comentent",
            new_name="Comment",
        ),
    ]
