# Generated by Django 6.0.6 on 2026-06-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_rename_comentent_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comentario",
            new_name="comment",
        ),
    ]
